### ISSUE TITLE
piety dependencies

### ISSUE THREAD

**Issue by MayaGans** [JohnCoene/javascript-for-r-comments#10]
```
dir.create("./inst/htmlwidgets/jquery", recursive = TRUE)
dir.create("./inst/htmlwidgets/typed")
```

Why do we use `recursive = TRUE` for jquery? Does this allow us to import all the files within a directory? 
Also - is the second directory a typo? `typed` should be `piety`? Am I missing something?

**Comment by JohnCoene** [comment]
Ah lord, well spotted! 

That's clearly wrong, it should indeed be:

```
dir.create("./inst/htmlwidgets/jquery")
dir.create("./inst/htmlwidgets/peity")
```

Thank you, I have fixed that in the book (not re-rendered yet) :)

**Comment by JohnCoene** [comment]
I closed that quick, sorry.

For context, I changed the entire chapter recently, it previously featured [typed.js](https://github.com/mattboldt/typed.js/) but according to reviewers caused confusion because this part of the book deals with "Visualisation" and this is just an animation: I thought it was fair and changed to another library :)
